name: Java CI

on:
  push:
  watch:
    types: [started]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Install packages
      run: mvn install --no-transfer-progress

    - name: Build with Maven
      run: mvn package
