name: Java CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        run: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32]
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn package -Dtoken=${{ secrets.READ_PACKAGES_TOKEN }}
